### PR TITLE
chore: setup docker compose for fossil api

### PR DESCRIPTION
**Pull request by cwkang1998**
Setup docker and docker compose for fossil api, allowing it to be ran locally with a local db instance running in docker.

Also added auto migration with this docker setup.

We can later re-use this for deployment if needed, but we should remove the db component and utilize an external db.

### CODE REVIEW

**Comment by ametel01** [comment]
what do you mean by "remove the db component and utilize an external db", could you give me an example?

**Comment by ametel01** [comment]
Looks good, please expand on the question above

**Review by ametel01 — APPROVED** [review]

**Comment by ametel01** [comment]
Ok i've got what you mean by removing the db service, we might create 2 separate compose files, the one you just created should be in the docker repo that @eugenPtr is building for testing, and the one living in fossil repo should be the one used in our CI/CD. Does this make sense?

**Comment by cwkang1998** [comment]
I would say the one without the db service should be whichever environment is production, with the db pointing to our actual db hosting. 

If @eugenPtr is using the service with the assumption that he needs the data in our current db then he should use the docker image without the db component. The one living in fossil repo (which is the one I've created in this PR) should be used for both local hosting and also ci cd.

**Pull request merged**
